version: "3.9"

services:
  archivebox:
    container_name: archivebox
    image: ${DOCKER_IMAGE:-archivebox:local}
    build: .
    cap_add:
      - ALL
    ports:
      - "8000:8000"
    volumes:
      - /mnt/usb/archivebox/data:/data
      - ./index.sqlite3:/data/index.sqlite3
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /run/dbus/system_bus_socket
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - SEARCH_BACKEND_ENGINE=sonic
      - SEARCH_BACKEND_HOST_NAME=sonic
      - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
      - ALLOWED_HOSTS=*
      - CHECK_SSL_VALIDITY=True
      - MEDIA_MAX_SIZE=1024m
      - CHROME_SANDBOX=False
      - CHROME_BINARY=google-chrome-beta
      - MEDIA_TIMEOUT=3600
      - PUBLIC_ADD_VIEW=False
      - PUBLIC_INDEX=True
      - PUBLIC_SNAPSHOTS=True
      - RIPGREP_BINARY=rga
      - SAVE_ARCHIVE_DOT_ORG=False
      - SAVE_FAVICON=False
      - SAVE_GIT=True
      - SAVE_MEDIA=True
      - SAVE_SCREENSHOT=False
      - SAVE_WARC=False
      - SAVE_WGET=True
      - SAVE_WGET_REQUISITES=True
      - TIMEOUT=600
      - URL_BLACKLIST = http(s)?:\/\/(.+)?(pornhub\.com)|(redgifs\.com)\/.*
  sonic:
    image: valeriansaliou/sonic:latest
    container_name: sonic
    expose:
      - 1491
    environment:
      - TZ=America/New_York
      - SEARCH_BACKEND_PASSWORD=SomeSecretPassword
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sonic.cfg:/etc/sonic.cfg:ro
      - ./data/sonic:/var/lib/sonic/store
